### ISSUE TITLE
Detect old test namespaces to prevent namespace explosions

### ISSUE THREAD

**Issue by ironcladlou** [openshift/monitor-project-lifecycle#24]
Now that namespaces are randomized, we must detect old test namespaces before starting a new test and delete them before proceeding. Otherwise a bug could cause the process to create an unbounded number of new test namespaces.

**Comment by twiest** [comment]
@ironcladlou What algorithm should we use to detect the old test namespaces?

We obviously need to be careful when deleting namespaces, so I want to make sure we agree on the detection algorithm.

I was thinking a regex for our namespace pattern + confirm the display name is set to the hard coded value in the code.

Is that sufficient?

**Comment by ironcladlou** [comment]
My hope was that we could do something simple like label the namespace on creation (e.g. `openshift-monitoring-test: monitor-app-create`), but since we're going through the ProjectRequest resource I'm not sure if we can create+label in a single request. I don't know if there's any way to make that possible with RBAC (cc @deads2k). Need to ask around about that. Then we could just select all namespaces matching the label each iteration. It would be possible to label the namespace post-creation, but there is still a small risk of us failing to update, thus orphaning the project. Seems unlikely, but possible.

Another far from ideal option would be to index namespaces on the `openshift.io/requester` annotation matching the current service account name. Silly, but it would work.

**Comment by joelsmith** [comment]
Besides just labeling it, should we also validate that we created it so that somebody dumb enough to label their ns with our label doesn't get it nuked?

**Comment by ironcladlou** [comment]
A label for selection and an annotation for the ownership check (e.g. `monitoring.openshift.io/availability-test: monitor-app-create`) would be nice.
